{% set name = "tabulatehelper" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa6a38812a6ed7c2efec976c8c4788a177f5ac06779731dc458323bc60bb97b8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - tabulate >=0.8.2

test:
  imports:
    - tabulatehelper

about:
  home: https://github.com/kiwi0fruit/tabulatehelper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Converts tabular data like Pandas dataframe to GitHub Flavored Markdown table (wrapper around tabulate module)."
  doc_url: https://github.com/kiwi0fruit/tabulatehelper
  dev_url: https://github.com/kiwi0fruit/tabulatehelper

extra:
  recipe-maintainers:
    - kiwi0fruit
